language: ruby
rvm:
- 2.1
script: bundle exec jekyll build
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAJU5O74NHBC2PUANQ
  secret_access_key:
    secure: "Wyh8A57b8JYMhQLJ20t75VFhKIztA6NlH/CtB3MG2gTu0ek/NaB3o9vYfjLaf6HhGwKWqIQi+CeU9Hg/g4fg5DM+JcxcyBZtzucf8YLm2It2QnsLSFhtX3mBoD5QCER/bHABfMRPRoAdyKAG+jf6S57EC+dFzNkrgrH0RWztkzhwLWELAA2R6NrxuiRQzUgz6qzYLbLsH5rdNgSWCDmMxBOAqtHrvE4cTJLe9/q/Ew0GSPYUZGtRf9fk4lYhU9400bLzBk0Vk43EIMFaE7J7w1HzP2dhYQ17VZzkbFfj0i3LEW/s951GTzb3nYcGmrKwQXSygVuOWcxdPo7Yne1OVICKRclNVO/c5NFx1y5aR7ytqTsefLYg3dg83ZuLNj6AJXPHUW86sMvtZ2O4ZzXj1+dpYf4WGko3yxrpU0QnR223TPTLMBllFRKBErON/kR7XxVihmM93H+qJgvxlfHRh0eHt6sxZNf/qlC8vN8cqiBC4VOfHQbiDcNuKKsWa2E1upgBNz1Oq2584v2zfR8VeFSfHeHi08boxeaE/bletPvOmzSfn/XdDtG0n5PpDrYuASMoQNX7nhbldB+0HIXaFe2O4li8sYGH/zBDF0rlhjoJ5xdVwNv8Q9v6RYX5KIuH4ertwOd647ixOfwT+EEUTXNQ4koQa4sVefG1MiPI1Vg="
  bucket: witch.coven.nu
  local-dir: _site
  endpoint: witch.coven.nu.s3-website-eu-central-1.amazonaws.com
  region: eu-central-1
  skip_cleanup: true
  cache_control: no-cache
