# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Wicked Witches
tagline:          Lajvförening
description:      "Förening som arrangerar lajv-evenemang."
url:              https://witch.coven.nu
baseurl:          /

#author:
#  name:           'Karlo Espiritu'
#  url:            https://twitter.com/karloespiritu

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/stanislavb/witch.coven.nu
